### ISSUE TITLE
possible to use an appender which recieves data?

### ISSUE THREAD

**Issue by henryw374** [cambium-clojure/cambium.core#4]
Hi,

I would like to log data, and also use an appender which receives that data, rather than a string, so for example it can write it to a database. Is this possible with cambium?

Thanks

**Comment by kumarshantanu** [comment]
Hi @henryw374 Cambium offers integration with the Logback backend. You can write a Logback appender that sends the log data to a database. For example, see the [RabbitMQ appender](https://github.com/cambium-clojure/cambium.logback.rabbitmq/blob/v0.4.4/java-src/cambium/logback/rabbitmq/RabbitAppender.java) that ships log events to a RabbitMQ instance.

This appender needs to be an AOT-compiled class (written in Java or in Clojure) so that the class name can be mentioned in the `logback.xml` file. You would have to provide the database credentials either in plaintext in the XML file, or derive from environment variables.

Hope this helps. Please feel free to continue the thread if you have more questions.

**Comment by henryw374** [comment]
ah thanks, I understand now. the appender gets an ILoggingEvent object
